### ISSUE TITLE
Publish latest version?

### ISSUE THREAD

**Issue by sudodoki** [mvasilkov/readability2#3]
Apparantly, based on what npm has as repo url, change https://github.com/mvasilkov/readability2/commit/09356e0992ed8997e3e41ad8457fde9e2b379cfd#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R19 didn't make it to published package. Would you be so kind to publish it?

**Comment by mvasilkov** [comment]
You're right, the repo field is bad for whatever reason.

All other files, however, are up to date.

¯\_(ツ)_/¯

**Comment by sudodoki** [comment]
non-issue, then?…
